### ISSUE TITLE
Still not working pro

### ISSUE THREAD

**Issue by tuanteku9x** [SkalaFrost/DuckChainBot#2]
Still not working pro!

**Comment by SkalaFrost** [comment]
dont raise issue without error info!

**Comment by tuanteku9x** [comment]
> dont raise issue without error info!

Hey, ducklings:

The DuckChain Bot upgrade is now complete! 🎉 Our team has worked diligently to enhance your experience, and we’re excited to bring you a smoother and more quacktastic interaction.

Thank you for your patience during this upgrade. The bot is back online and ready to assist you!

Let’s restart quacking now. Happy quacking! 
=================================
But

2024-09-06 08:20:23 | ERROR | Error in function 'make_request': 404, message='Not Found', url=URL('https://tgapi.duckchain.io/user/info')
2024-09-06 08:20:24 | ERROR | teku | Unknown error: 'NoneType' object has no attribute 'get'

**Comment by SkalaFrost** [comment]
try out new version, thanks
