### ISSUE TITLE
more tasks should be supported

### ISSUE THREAD

**Issue by leochan-coder** [SkalaFrost/DuckChainBot#3]
The script currently only supports basic tasks. Are there other tasks that can be supported in the app, such as daily sign-in, adding mini apps, etc.

**Comment by SkalaFrost** [comment]
Duckchain mini app currently has 4 quests, br

**Comment by leochan-coder** [comment]
![IMG_0206](https://github.com/user-attachments/assets/ee00dc0b-47d6-4d7e-9204-3f772ff0094f)
More 4
